added a "sketch" of repo, entity and service
kaiiiseeel/book-store pull request #1
Opened 2024-04-18 12:13 UTC by kaiiiseeel

2024-04-18 15:20 UTC, andrii-hoienko requested changes

2024-04-18 15:20 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/repository/impl/BookRepositoryImpl.java
> +        return null;
Implement logic

2024-04-18 15:20 UTC, andrii-hoienko commented on src/main/resources/application.properties
> +spring.datasource.username=sa
Don`t push creadentials

2024-04-22 07:21 UTC, karma-o approved these changes
Left a minor comment and approved

2024-04-22 07:21 UTC, karma-o commented on src/main/java/mate/academy/bookstore/entity/Book.java
> +public class Book {
this is not critical for now, but `@Data` is not recommended for use with `@Entity`, details on that:
https://medium.com/@dev.fethi/data-anatation-and-hibernate-n-1-problems-466df982288e

2024-04-22 11:25 UTC, merged