Added shopping cart to the project
kaiiiseeel/book-store pull request #10
Opened 2024-05-22 20:36 UTC by kaiiiseeel

2024-05-24 15:38 UTC, d1sam requested changes
Good job, but there are some minor changes, that should be done according to my comments.

2024-05-24 15:38 UTC, d1sam commented on src/main/java/mate/academy/bookstore/entity/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```

2024-05-24 15:38 UTC, d1sam commented on src/main/java/mate/academy/bookstore/entity/CartItem.java
> +    private int quantity;
```suggestion
    @Column(nullable = false)
    private int quantity;
```

2024-05-24 15:38 UTC, d1sam commented on src/main/java/mate/academy/bookstore/entity/ShoppingCart.java
> +    @OneToOne
```suggestion
    @OneToOne(fetch = FetchType.LAZY)
```

2024-05-24 15:38 UTC, d1sam commented on src/main/resources/db/changelog/changes/14-create-cart-items-table.yaml
let's add unique constraint to book_id, shopping_cart_id

2024-05-24 15:38 UTC, d1sam commented on src/main/java/mate/academy/bookstore/service/impl/UserServiceImpl.java
>      @Override
```suggestion
    @Override
    @Transactional
```

2024-05-24 15:38 UTC, d1sam commented on src/main/java/mate/academy/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2024-05-24 15:38 UTC, d1sam commented on src/main/java/mate/academy/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    public ShoppingCartResponseDto addItem(Long id, CartItemRequestDto requestDto) {
```suggestion
    @Transactional
    public ShoppingCartResponseDto addItem(Long id, CartItemRequestDto requestDto) {

```

2024-05-27 07:59 UTC, karma-o approved these changes
GJ! Also, please take a look at my comments before merging

2024-05-27 07:59 UTC, karma-o commented on src/main/java/mate/academy/bookstore/service/impl/ShoppingCartServiceImpl.java
> +                );
we should also validate if that cart belongs to user who is making that request, otherwise it won't be secure

2024-05-27 07:59 UTC, karma-o commented on src/main/java/mate/academy/bookstore/service/impl/ShoppingCartServiceImpl.java
> +                );
same here

2024-05-27 07:59 UTC, karma-o commented on src/main/java/mate/academy/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        cartItemRepository.deleteById(id);
and here

2024-06-06 13:30 UTC, merged