added readme and license
kaiiiseeel/book-store pull request #13
Opened 2024-05-29 19:14 UTC by kaiiiseeel

2024-05-30 10:05 UTC, karma-o requested changes
Looks very nice! left a few suggestions

2024-05-30 10:05 UTC, karma-o commented on README.md
> +- **JUnit & Mockito**: For testing
we can also add testcontainers to the list of testing tools

2024-05-30 10:05 UTC, karma-o commented on README.md
> +- **GitHub Actions**: CI (Continues integration) tool
```suggestion
- **GitHub Actions**: CI (Continuous integration) tool
```

2024-05-30 10:05 UTC, karma-o commented on README.md
> +</details>
this section is quite important we can expand it to explain things more about how your auth is working in the app, leave a request/response examples, how to use the token that we receive, and leave credentials to simple and admin users, so that the visitor of your project could use them for testing purposes

2024-05-30 10:05 UTC, karma-o commented on README.md
> +## 🚀 Project functionality
I'd move swagger and a postman collection links to here

2024-05-30 10:05 UTC, karma-o commented on README.md
> +```
not sure this step is necessary if we are using docker-compose, please double-check

2024-05-30 10:05 UTC, karma-o commented on README.md
> +## 💡 How to install
let's move that section to the top, somewhere after `Technologies` maybe?

2024-05-30 10:05 UTC, karma-o commented on README.md
> +1. Open documentation at `http://localhost:8088/swagger-ui.html`
link is unclickable, do not put links in \`\`
```suggestion
1. Open documentation at http://localhost:8088/swagger-ui.html
```

2024-05-30 10:05 UTC, karma-o commented on README.md
think about recording a video demonstration of how your project is working, could be very beneficial in terms of converting sent CV's into interviews

2024-05-30 10:05 UTC, karma-o commented on README.md
you can also add a link to the deployed project once you will have it later on

2024-06-10 18:50 UTC, kaiiiseeel commented
Will add video overview in a few days

2024-06-12 08:48 UTC, karma-o approved these changes
Well done!

2024-06-12 08:48 UTC, karma-o commented on README.md
> +spring.datasource.password=your_db_password
we could use ENV variables here as well

2024-06-30 18:26 UTC, merged