added liquibase and Spring Boot Data JPA to the project
kaiiiseeel/book-store pull request #3
Opened 2024-04-27 13:03 UTC by kaiiiseeel

2024-04-29 08:38 UTC, karma-o requested changes
Looks good so far, left some minor comments

2024-04-29 08:38 UTC, karma-o commented on src/main/java/mate/academy/bookstore/controller/BookController.java
> +    @DeleteMapping("/{id}")
add `no content` response status to here, and `created` for the post endpoint that you already have

2024-04-29 08:38 UTC, karma-o commented on src/main/java/mate/academy/bookstore/controller/BookController.java
> +                                  @RequestBody CreateBookRequestDto requestDto) {
It isn't just for creation anymore
```suggestion
                                  @RequestBody BookRequestDto requestDto) {

```

2024-04-29 08:38 UTC, karma-o commented on src/main/java/mate/academy/bookstore/service/impl/BookServiceImpl.java
> +        throw new EntityNotFoundException("Can't delete book with such id: " + id);
let's flip this if to follow up with the fail/return early pattern
```suggestion
        if (!bookRepository.existsById(id)) {
            throw new EntityNotFoundException("Can't delete book with such id: " + id);
        }
        bookRepository.deleteById(id);
```

2024-04-29 08:38 UTC, karma-o commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                    nullable: false
`primaryKey` already has `nullable false` inside it
```suggestion
                    primaryKey: true
```

2024-04-29 08:38 UTC, karma-o commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                    nullable: false
```suggestion
                    nullable: false

```

2024-04-29 08:38 UTC, karma-o commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/01-create-books-table.yaml
```suggestion
      file: db/changelog/changes/01-create-books-table.yaml

```

2024-04-29 08:38 UTC, karma-o commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                  type: varchar(255)
I'd make those fields at least 500

2024-04-29 13:42 UTC, andrii-hoienko requested changes
Nice, left minor comments

2024-04-29 13:42 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/entity/Book.java
> +
```suggestion
```

2024-04-29 13:42 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/impl/BookServiceImpl.java
> +        }
Why you check existence on delete but do not check on update?

2024-04-29 13:42 UTC, andrii-hoienko commented on src/main/resources/application.properties
> +
```suggestion
```

2024-04-30 07:04 UTC, karma-o approved these changes

2024-04-30 07:05 UTC, merged