Added User entity to the project
kaiiiseeel/book-store pull request #6
Opened 2024-05-09 20:28 UTC by kaiiiseeel

2024-05-10 13:23 UTC, andrii-hoienko requested changes
Good job! Left minor comments

2024-05-10 13:23 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/entity/User.java
> +public class User {
Soft delete should be applied to user as well

2024-05-10 13:23 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/impl/UserServiceImpl.java
> +            throw new RegistrationException("The user with this email is already registered");
```suggestion
            throw new RegistrationException("The user with this email: EMAIL is already registered");

```

2024-05-10 13:23 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/validation/FieldMatchValidator.java
> +        return Objects.equals(requestDto.getPassword(), requestDto.getRepeatedPassword());
This annotation works only with password and repeatedPassword, but it should work with 2 any fields, that is defined in annotation properties

2024-05-10 13:23 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  type: varchar(500)
```suggestion
                  type: varchar(500)
                  
```

2024-05-13 08:49 UTC, karma-o approved these changes
GJ! Approved with several comments for improvement

2024-05-13 08:49 UTC, karma-o commented on src/main/java/mate/academy/bookstore/service/impl/UserServiceImpl.java
> +        if (userRepository.findAllByEmail(requestDto.getEmail()).isPresent()) {
a bit more efficient and simple
```suggestion
        if (userRepository.existsByEmail(requestDto.getEmail())) {
```

2024-05-13 08:49 UTC, karma-o commented on src/main/java/mate/academy/bookstore/validation/FieldMatchValidator.java
> +        Object firstObject = new BeanWrapperImpl(value).getPropertyValue(firstField);
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/BeanWrapperImpl.html
> NOTE: As of Spring 2.5, this is - for almost all purposes - an internal class. It is just public in order to allow for access from other framework packages. For standard application access purposes, use the [PropertyAccessorFactory.forBeanPropertyAccess(java.lang.Object)](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/PropertyAccessorFactory.html#forBeanPropertyAccess(java.lang.Object)) factory method instead.

First time seeing this class, so not sure how it works and what it does, had to google it and found out that it is not recommended. overall we could have used simple reflection by getting the class of `value` var and getting a field by `class.getDeclaredField(field)` to then compare the values of those 2 fields.

2024-05-13 08:49 UTC, karma-o commented on src/main/java/mate/academy/bookstore/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(exception.getMessage(), HttpStatus.CONFLICT);
if these return plain text, we should change it to some json with timestamp, status phrase and message fields

2024-05-14 07:09 UTC, merged