added security to the project
kaiiiseeel/book-store pull request #7
Opened 2024-05-14 08:23 UTC by kaiiiseeel

2024-05-14 11:47 UTC, Eidenn005 approved these changes
LGTM

2024-05-14 13:18 UTC, andrii-hoienko requested changes
Nice, left some minor comments

2024-05-14 13:18 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/config/SecurityConfig.java
> +@EnableMethodSecurity
```suggestion
@EnableMethodSecurity
@RequiredArgsConstructor
```

2024-05-14 13:18 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/config/SecurityConfig.java
> +    }
```suggestion

```

2024-05-14 13:18 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/03-create-roles-table.yaml
> +                    unique: true
```suggestion
                    unique: true
                    
```

2024-05-14 13:18 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/04-create-users-roles-table.yaml
> +                    references: roles(id)
```suggestion
                    references: roles(id)
                    
```

2024-05-14 13:18 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/05-insert-roles-to-roles-table.yaml
> +                  value: ADMIN
```suggestion
                  value: ADMIN
                  
```

2024-05-14 13:18 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/06-insert-users-to-users-table.yaml
> +                  value: '789 Oak St'
```suggestion
                  value: '789 Oak St'
                  
```

2024-05-15 09:28 UTC, vovasalyha approved these changes
Approving, but take a look on one comment.

2024-05-15 09:28 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/04-create-users-roles-table.yaml
> +            tableName: users_roles
Make user_id + role_id a composite PK to disallow duplicate entries.

2024-05-15 18:07 UTC, merged