Added category entity to the project
kaiiiseeel/book-store pull request #9
Opened 2024-05-17 12:51 UTC by kaiiiseeel

2024-05-20 10:42 UTC, yevheniisynytsia requested changes
Well done! Left some suggestions

2024-05-20 10:42 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookstore/entity/Book.java
> +    @ManyToMany(fetch = FetchType.EAGER)
```suggestion
    @ManyToMany(fetch = FetchType.LAZY)
```

2024-05-20 10:42 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookstore/entity/Book.java
> +    private Set<Category> categories = new HashSet<>();
please exclude from equals hashcode tostring

2024-05-20 10:42 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookstore/entity/Category.java
> +
```suggestion
```

2024-05-20 10:42 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookstore/mapper/CategoryMapper.java
> +
```suggestion
```

2024-05-20 10:42 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookstore/service/impl/CategoryServiceImpl.java
> +        }
if is duplicated, can be extracted into a separate method

2024-05-20 13:22 UTC, andrii-hoienko requested changes
Good job! Left some comments

2024-05-20 13:22 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/impl/CategoryServiceImpl.java
> +
```suggestion

```

2024-05-20 13:22 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/impl/BookServiceImpl.java
>          return bookMapper.toDto(bookRepository.save(book));
You need to save and validate categories as well here

2024-05-20 13:22 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/repository/BookRepository.java
> +
```suggestion

```

2024-05-21 16:50 UTC, andrii-hoienko requested changes
Nice, left some comments

2024-05-21 16:50 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/impl/BookServiceImpl.java
> +        }
Move thos to separate method

2024-05-21 16:50 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/service/impl/BookServiceImpl.java
> +            categoryIds.removeAll(availableCategories);
What is the reason to make some removal logic, all you need is compare size to realize that all categories are present

2024-05-21 17:04 UTC, merged